INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (1, '2017-07-11', 'China', 'Xinying', '', 93, false);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (4, '2018-04-26', 'Indonesia', 'Ketapang', '', 53, false);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (3, '2017-08-18', 'Greece', 'Kallithéa', '', 31, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (2, '2019-08-21', 'China', 'Jinjiang', '', 38, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (5, '2020-04-27', 'Panama', 'Capira', '', 36, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (6, '2018-11-23', 'Japan', 'Itoigawa', '', 81, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (7, '2017-05-16', 'Uruguay', 'Salto', '', 43, false);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (8, '2016-09-08', 'Greece', 'Áno Liósia', '', 94, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (9, '2020-12-10', 'Portugal', 'Azenhas do Mar', 'Lisboa', 5, false);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (11, '2020-07-03', 'China', 'Chishui', '', 9, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (10, '2019-06-22', 'Albania', 'Helmas', '', 7, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (13, '2016-12-06', 'France', 'Alençon', 'Basse-Normandie', 44, false);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (12, '2020-01-06', 'France', 'Quimper', 'Bretagne', 77, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (14, '2018-04-01', 'Japan', 'Ushiku', '', 13, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (15, '2021-04-28', 'Mexico', 'Fovissste', 'Chihuahua', 26, true);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (16, '2017-09-21', 'China', 'Xiaojin', '', 7, false);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (17, '2019-08-31', 'Syria', 'Khān Shaykhūn', '', 4, false);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (18, '2020-12-25', 'Argentina', 'Zapala', '', 54, false);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (19, '2016-04-25', 'Philippines', 'Unidad', '', 72, false);

INSERT INTO ADVENTURES (ID, ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES (20, '2016-04-01', 'Brazil', 'Maraã', '', 56, true);
