INSERT INTO ADVENTURES (ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES ('2017-07-11', 'China', 'Xinying', '', 93, false);
INSERT INTO ADVENTURES (ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES ('2018-03-22', 'USA', 'San Francisco', 'CA', 120, true);
INSERT INTO ADVENTURES (ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES ('2019-11-05', 'Italy', 'Rome', '', 75, true);
INSERT INTO ADVENTURES (ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES ('2020-06-15', 'Brazil', 'Rio de Janeiro', '', 110, false);
INSERT INTO ADVENTURES (ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES ('2021-09-30', 'Australia', 'Sydney', '', 85, true);
INSERT INTO ADVENTURES (ADVENTURE_DATE, COUNTRY, CITY, STATE, NUM_PHOTOS, BLOG_COMPLETED)
VALUES ('2022-12-12', 'Japan', 'Tokyo', '', 130, false);